version: '3.9'

services:
  flask-app:
    image: bohdan004/flask:latest
    container_name: flask-app
    user: flask
    ports:
      - "8000:8000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 1m
    networks:
      - flask-app

networks:
  flask-app:
    driver: bridge
