version: '3.9'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: root
    expose:
      - 9090
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/config:/etc/prometheus/
      - ./prometheus/data:/prometheus
    healthcheck:
      test: ["CMD", "wget", "http://localhost:9090"]
      interval: 10s
      timeout: 15s
      retries: 10
      start_period: 40s 
    networks:
      - grafana
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: root
    ports:
      - 3000:3000
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.dns.navy/
    volumes:
      - ./grafana_data:/var/lib/grafana
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 1m
    networks:
      - grafana
    restart: always

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    restart: always
    devices:
      - "/dev/kmsg:/dev/kmsg"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro 
    networks:
      - grafana
    expose:
      - 8080
  
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: always
    expose:
      - 9100
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - grafana
        
networks:
  grafana:
    driver: bridge
