version: "3.9"
services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    user: root
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "./jenkins_data/jenkins_home:/var/jenkins_home"
      - "./plugins.txt:/usr/share/jenkins/ref/plugins.txt"
      - "./casc.yaml:/var/jenkins_home/casc.yaml"
    environment:
      CASC_JENKINS_CONFIG: /var/jenkins_home/casc.yaml
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
    command: ["/bin/bash", "-c", "jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt && /usr/bin/tini -- /usr/local/bin/jenkins.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login"]
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 1m
    networks:
      - jenkins

networks:
  jenkins:
    driver: bridge